version: "3.8"
services:
  weaviate:
    image: semitechnologies/weaviate:1.28.5
    restart: always
    ports:
      - 8080:8080
      - 50051:50051
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
